// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfUHSGFhAw1Aljtm2vR-a22O3SagFsqcA',
    appId: '1:28073183683:web:9065b2ba66ea08c638d576',
    messagingSenderId: '28073183683',
    projectId: 'onyx-customer-order-e8b2c',
    authDomain: 'onyx-customer-order-e8b2c.firebaseapp.com',
    storageBucket: 'onyx-customer-order-e8b2c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt0G_veoBbXmkvwODZri7CX_ipGmnmjpc',
    appId: '1:28073183683:android:307fd8a08ddb03c538d576',
    messagingSenderId: '28073183683',
    projectId: 'onyx-customer-order-e8b2c',
    storageBucket: 'onyx-customer-order-e8b2c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfUHSGFhAw1Aljtm2vR-a22O3SagFsqcA',
    appId: '1:28073183683:web:2dd4e831ff2f40a738d576',
    messagingSenderId: '28073183683',
    projectId: 'onyx-customer-order-e8b2c',
    authDomain: 'onyx-customer-order-e8b2c.firebaseapp.com',
    storageBucket: 'onyx-customer-order-e8b2c.firebasestorage.app',
  );
}
